# Generated by Django 5.1.3 on 2026-04-12 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, '单选题'), (2, '多选题'), (3, '判断题'), (4, '简答题')], verbose_name='题型')),
                ('content', models.TextField(verbose_name='题干内容(SM4密文)')),
                ('media_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='媒体文件路径')),
                ('options', models.TextField(blank=True, null=True, verbose_name='选项(SM4密文)')),
                ('answer', models.TextField(verbose_name='答案(SM4密文)')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='解析(SM4密文)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='courses.course', verbose_name='所属课程')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
                'db_table': 'questions_question',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='q_type_idx'), models.Index(fields=['created_at'], name='q_created_at_idx'), models.Index(fields=['created_by', 'created_at'], name='q_creator_crt_idx')],
            },
        ),
    ]
