# Generated by Django 5.1.3 on 2026-04-12 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码(SM3哈希)')),
                ('salt', models.CharField(max_length=32, verbose_name='动态盐值')),
                ('real_name', models.TextField(verbose_name='真实姓名(SM4密文)')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='手机号(SM4密文)')),
                ('role', models.SmallIntegerField(choices=[(0, '管理员'), (1, '教师'), (2, '学生')], default=2, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('student_class', models.ForeignKey(blank=True, limit_choices_to={'id__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users_user',
                'indexes': [models.Index(fields=['role'], name='user_role_idx'), models.Index(fields=['is_active'], name='user_active_idx'), models.Index(fields=['role', 'is_active'], name='user_role_act_idx')],
            },
        ),
    ]
