# Generated by Django 5.1.3 on 2026-04-12 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('courses', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='试卷标题')),
                ('total_score', models.IntegerField(default=100, verbose_name='总分')),
                ('duration', models.IntegerField(verbose_name='考试时长(分钟)')),
                ('question_config', models.JSONField(default=dict, verbose_name='题目配置(JSON)')),
                ('status', models.SmallIntegerField(choices=[(0, '草稿'), (1, '已发布')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='courses.course', verbose_name='所属课程')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_papers', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_classes', models.ManyToManyField(blank=True, related_name='papers_to_take', to='classes.class', verbose_name='指定班级')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'papers_paper',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='分值')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.paper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目',
                'db_table': 'papers_paperquestion',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['status'], name='paper_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['created_at'], name='paper_crt_at_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['status', 'created_at'], name='paper_st_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['created_by', 'created_at'], name='paper_cr_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='paperquestion',
            index=models.Index(fields=['paper', 'order'], name='pq_paper_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperquestion',
            unique_together={('paper', 'question')},
        ),
    ]
