# Generated by Django 5.1.3 on 2026-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('institution', models.CharField(max_length=100, verbose_name='所属机构')),
                ('description', models.TextField(blank=True, null=True, verbose_name='班级描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'classes_class',
                'ordering': ['-created_at'],
            },
        ),
    ]
