# Generated by Django 5.1.3 on 2026-04-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='classes', to='courses.course', verbose_name='关联课程'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['major'], name='class_major_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['institution'], name='class_inst_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['major', 'institution'], name='class_maj_inst_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'major', 'institution')},
        ),
    ]
