# Generated by Django 5.1.3 on 2026-04-12 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('student_answers', models.TextField(blank=True, null=True, verbose_name='学生答案(SM4密文)')),
                ('score', models.TextField(blank=True, null=True, verbose_name='得分(SM4密文)')),
                ('status', models.SmallIntegerField(choices=[(0, '进行中'), (1, '批改中'), (2, '教师已阅卷'), (3, '已完成')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to='papers.paper', verbose_name='试卷')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试记录',
                'verbose_name_plural': '考试记录',
                'db_table': 'exams_examrecord',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='学生答案(SM4密文)')),
                ('score', models.TextField(blank=True, null=True, verbose_name='得分(SM4密文)')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examrecord', verbose_name='考试记录')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '学生答案',
                'verbose_name_plural': '学生答案',
                'db_table': 'exams_studentanswer',
            },
        ),
        migrations.CreateModel(
            name='MistakeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('exam_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='exams.examrecord', verbose_name='考试记录')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='questions.question', verbose_name='题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('student_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mistake_entries', to='exams.studentanswer', verbose_name='学生答案记录引用')),
            ],
            options={
                'verbose_name': '错题本',
                'verbose_name_plural': '错题本',
                'db_table': 'exams_mistakebook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['status'], name='er_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['student', 'status'], name='er_stu_st_idx'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['paper', 'status'], name='er_paper_st_idx'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['student', 'created_at'], name='er_stu_crt_idx'),
        ),
        migrations.AddIndex(
            model_name='examrecord',
            index=models.Index(fields=['paper', 'created_at'], name='er_paper_crt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('exam_record', 'question')},
        ),
        migrations.AddIndex(
            model_name='mistakebook',
            index=models.Index(fields=['student', 'created_at'], name='mb_stu_crt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mistakebook',
            unique_together={('student', 'question', 'exam_record')},
        ),
    ]
